### PR TITLE
Update Dockerfile to use latest b2aiprep

### PR DESCRIPTION
**Pull request by satra**
@quinnwai - a version update to b2aiprep. please let us know when this is available in the cloud workspace.

### CODE REVIEW

**Comment by satra** [comment]
@quinnwai - hold off on merging this. we are going to push another update to b2aiprep

**Comment by quinnwai** [comment]
Sounds good. Tested locally that the first update was successful, will wait on your cue

**Comment by quinnwai** [comment]
@satra let me know when this is ready to merge

**Comment by satra** [comment]
ready to merge

**Comment by quinnwai** [comment]
Awesome! Will add a commit for an init script, test, and handle the merge. Will let you know when the image has been updated in the workspace. Cheers!

**Pull request merged**
